library(data.table)
library(lubridate)
housecoms_all<-read.table("household_power_consumption.txt",header = TRUE, sep = ";")
housecoms_all$Date_Time<-as.POSIXct(dmy_hms(paste(housecoms_all$Date,housecoms_all$Time)))
housecoms_sub<-housecoms_all[year(housecoms_all$Date_Time)==2007 & month(housecoms_all$Date_Time)==2 & mday(housecoms_all$Date_Time) %in% c(1,2),c("Date_Time","Sub_metering_1","Sub_metering_2","Sub_metering_3")]
rm(list="housecoms_all")
housecoms_sub$Sub_metering_1<-as.numeric(as.character(housecoms_sub$Sub_metering_1))
housecoms_sub$Sub_metering_2<-as.numeric(as.character(housecoms_sub$Sub_metering_2))
housecoms_sub$Sub_metering_3<-as.numeric(as.character(housecoms_sub$Sub_metering_3))
png(filename = "plot3.png", height = 480, width = 480)
with(housecoms_sub,plot(Sub_metering_1~Date_Time, xlab = "", ylab = "Energy sub metering", type = "l",  col = "black"))
with(housecoms_sub,lines(Sub_metering_2~Date_Time, xlab = "", ylab = "Energy sub metering", type = "l",  col = "red"))
with(housecoms_sub,lines(Sub_metering_3~Date_Time, xlab = "", ylab = "Energy sub metering", type = "l",  col = "blue"))
legend("topright",  lty = 1, col = c("black", "red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()